### ISSUE TITLE
Cannot import name SetuptoolsVersion

### ISSUE THREAD

**Issue by avoinea** [plone/plone.versioncheck#5]
**$ bin/versioncheck -b deployment.cfg**
```
Traceback (most recent call last):
  File "bin/versioncheck", line 9, in <module>
    load_entry_point('plone.versioncheck==1.0', 'console_scripts', 'versioncheck')()
  File "/var/local/bise/bise.plonebuildout/lib/python2.7/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/var/local/bise/bise.plonebuildout/lib/python2.7/site-packages/pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "/var/local/bise/bise.plonebuildout/lib/python2.7/site-packages/pkg_resources.py", line 2184, in load
    ['__name__'])
  File "/var/local/bise/bise.plonebuildout/lib/python2.7/site-packages/plone/versioncheck/script.py", line 5, in <module>
    from plone.versioncheck.pypi import check_all
  File "/var/local/bise/bise.plonebuildout/lib/python2.7/site-packages/plone/versioncheck/pypi.py", line 4, in <module>
    from pkg_resources import SetuptoolsVersion
ImportError: cannot import name SetuptoolsVersion
```

**Comment by jensens** [comment]
what version of setuptools are you using?

**Comment by avoinea** [comment]
7.0

**Comment by jensens** [comment]
hmm, an older one, it needs at least 12 - i stated that in the setup.py
