### ISSUE TITLE
v1.1 - KeyError: 'tracking'

### ISSUE THREAD

**Issue by avoinea** [plone/plone.versioncheck#9]
```
Read tracking information from buildout extension: 
- .plone.versioncheck.tracked.json
 - [Errno 2] No such file or directory: '.plone.versioncheck.tracked.json'
Traceback (most recent call last):
  File "/joint/python/bin/versioncheck", line 9, in <module>
    load_entry_point('plone.versioncheck==1.1', 'console_scripts', 'versioncheck')()
  File "/joint/python/local/lib/python2.7/site-packages/plone/versioncheck/script.py", line 87, in run
    tracking.get(pkgsinfo, args.buildout)
  File "/joint/python/local/lib/python2.7/site-packages/plone/versioncheck/tracking.py", line 86, in get
    delta = time.time() - pkginfo['tracking']['generated']
KeyError: 'tracking'
```

Also if I use the `-n` with `-i` it doesn't seem to work:

```
$ versioncheck -n -i versions.cfg > with-n.txt
$ versioncheck -i versions.cfg > without-n.txt
$ diff with-n.txt without-n.txt
Nothing
```

Try it on https://github.com/eea/eea.plonebuildout.example.git

**Comment by jensens** [comment]
solved in and released with 1.1.1
